/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Left_Button_aliases.h"
#include "Left_Button.h"
#include "Right_Button_aliases.h"
#include "Right_Button.h"
#include "PWM_1.h"
#include "PWM_2.h"
#include "Left_LED_aliases.h"
#include "Left_LED.h"
#include "Right_LED_aliases.h"
#include "Right_LED.h"
#include "Clock_1.h"
#include "isr_Left_Button.h"
#include "UART_1.h"
#include "isr_Right_Button.h"
#include "timer_clock.h"
#include "Timer_1.h"
#include "isr_Timer_1.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

